//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Company.MobileDSL
{
	internal static partial class Constants
	{
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string DesignerFileExtension = "mdsl";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string ProductName = @"MobileDSL";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string CompanyName = @"Company";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string ProductVersion = "1.0.0.0";

		// Menu definitions
		public static readonly global::System.ComponentModel.Design.CommandID MobileDSLDiagramMenu = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(MobileDSLCommandSetId), 0x10000);
		public static readonly global::System.ComponentModel.Design.CommandID MobileDSLExplorerMenu = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(MobileDSLCommandSetId), 0x10001);

		// Command definitions
		public static readonly global::System.ComponentModel.Design.CommandID ViewMobileDSLExplorerCommand = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(MobileDSLCommandSetId), 0x0001);
	
		// Package identifier
		public const string MobileDSLPackageId = "54424d5f-5c62-4e39-b1f1-c4ea0a71f254";
		
		// Editor factory identifier
		public const string MobileDSLEditorFactoryId = "5655060c-ef72-481b-b551-6d87cbd1b4bf";
		
		public const string DefaultDiagramExtension = ".diagram";
		
		// Model explorer tool window identifier
		public const string MobileDSLModelExplorerToolWindowId = "43d9d581-3d29-4e23-b95f-81c2087f2c38";
	}
}
//
// Constants not generated from values in DesignerDefinition.dsl are defined below
//
namespace Company.MobileDSL
{
	internal static partial class Constants
	{
		// Menu identifier
		public const string MobileDSLCommandSetId = "06e21da2-83e3-4bd6-9608-3974e9d2762c";
	}
}