//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using VSShellInterop = global::Microsoft.VisualStudio.Shell.Interop;
using VSShell = global::Microsoft.VisualStudio.Shell;
using DslShell = global::Microsoft.VisualStudio.Modeling.Shell;
using DslDesign = global::Microsoft.VisualStudio.Modeling.Design;
using DslModeling = global::Microsoft.VisualStudio.Modeling;
using System;
using System.Diagnostics;
using System.Drawing.Design;
using System.Linq;
using System.Windows.Forms;
	
namespace Company.MobileDSL
{
	/// <summary>
	/// This class implements the VS package that integrates this DSL into Visual Studio.
	/// </summary>
	[VSShell::DefaultRegistryRoot("Software\\Microsoft\\VisualStudio\\15.0")]
	[VSShell::PackageRegistration(RegisterUsing = VSShell::RegistrationMethod.Assembly, UseManagedResourcesOnly = true)]
	[VSShell::ProvideToolWindow(typeof(MobileDSLExplorerToolWindow), MultiInstances = false, Style = VSShell::VsDockStyle.Tabbed, Orientation = VSShell::ToolWindowOrientation.Right, Window = "{3AE79031-E1BC-11D0-8F78-00A0C9110057}")]
	[VSShell::ProvideToolWindowVisibility(typeof(MobileDSLExplorerToolWindow), Constants.MobileDSLEditorFactoryId)]
	[VSShell::ProvideStaticToolboxGroup("@MobileDSLToolboxTab;Company.MobileDSL.Dsl.dll", "Company.MobileDSL.MobileDSLToolboxTab")]
	[VSShell::ProvideStaticToolboxItem("Company.MobileDSL.MobileDSLToolboxTab",
					"@InPortToolboxItem;Company.MobileDSL.Dsl.dll", 
					"Company.MobileDSL.InPortToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"CreateInPortF1Keyword", 
					"@InPortToolboxBitmap;Company.MobileDSL.Dsl.dll", 
					0xff00ff,
					Index = 0)]
	[VSShell::ProvideStaticToolboxItem("Company.MobileDSL.MobileDSLToolboxTab",
					"@OutPortToolboxItem;Company.MobileDSL.Dsl.dll", 
					"Company.MobileDSL.OutPortToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"CreateOutPortF1Keyword", 
					"@OutPortToolboxBitmap;Company.MobileDSL.Dsl.dll", 
					0xff00ff,
					Index = 1)]
	[VSShell::ProvideStaticToolboxItem("Company.MobileDSL.MobileDSLToolboxTab",
					"@ConnectionToolboxItem;Company.MobileDSL.Dsl.dll", 
					"Company.MobileDSL.ConnectionToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"ConnectAssociationF1Keyword", 
					"@ConnectionToolboxBitmap;Company.MobileDSL.Dsl.dll", 
					0xff00ff,
					Index = 2)]
	[VSShell::ProvideStaticToolboxItem("Company.MobileDSL.MobileDSLToolboxTab",
					"@CommentToolboxItem;Company.MobileDSL.Dsl.dll", 
					"Company.MobileDSL.CommentToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"ConnectCommentF1Keyword", 
					"@CommentToolboxBitmap;Company.MobileDSL.Dsl.dll", 
					0xff00ff,
					Index = 3)]
	[VSShell::ProvideStaticToolboxItem("Company.MobileDSL.MobileDSLToolboxTab",
					"@CommentConnectorToolboxItem;Company.MobileDSL.Dsl.dll", 
					"Company.MobileDSL.CommentConnectorToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"ConnectCommentsReferenceTypesF1Keyword", 
					"@CommentConnectorToolboxBitmap;Company.MobileDSL.Dsl.dll", 
					0xff00ff,
					Index = 4)]
	[VSShell::ProvideStaticToolboxItem("Company.MobileDSL.MobileDSLToolboxTab",
					"@State_oldToolboxItem;Company.MobileDSL.Dsl.dll", 
					"Company.MobileDSL.State_oldToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"State_old", 
					"@State_oldToolboxBitmap;Company.MobileDSL.Dsl.dll", 
					0xff00ff,
					Index = 5)]
	[VSShell::ProvideStaticToolboxItem("Company.MobileDSL.MobileDSLToolboxTab",
					"@StateConnectionToolboxItem;Company.MobileDSL.Dsl.dll", 
					"Company.MobileDSL.StateConnectionToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"StateConnection", 
					"@StateConnectionToolboxBitmap;Company.MobileDSL.Dsl.dll", 
					0xff00ff,
					Index = 6)]
	[VSShell::ProvideStaticToolboxItem("Company.MobileDSL.MobileDSLToolboxTab",
					"@InPortConnectionToolboxItem;Company.MobileDSL.Dsl.dll", 
					"Company.MobileDSL.InPortConnectionToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"InPortConnection", 
					"@InPortConnectionToolboxBitmap;Company.MobileDSL.Dsl.dll", 
					0xff00ff,
					Index = 7)]
	[VSShell::ProvideStaticToolboxItem("Company.MobileDSL.MobileDSLToolboxTab",
					"@ShowFormToPortConnectionToolboxItem;Company.MobileDSL.Dsl.dll", 
					"Company.MobileDSL.ShowFormToPortConnectionToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"ShowFormToPortConnection", 
					"@ShowFormToPortConnectionToolboxBitmap;Company.MobileDSL.Dsl.dll", 
					0xff00ff,
					Index = 8)]
	[VSShell::ProvideStaticToolboxItem("Company.MobileDSL.MobileDSLToolboxTab",
					"@IPToolboxItem;Company.MobileDSL.Dsl.dll", 
					"Company.MobileDSL.IPToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"IP", 
					"@IPToolboxBitmap;Company.MobileDSL.Dsl.dll", 
					0xff00ff,
					Index = 9)]
	[VSShell::ProvideStaticToolboxItem("Company.MobileDSL.MobileDSLToolboxTab",
					"@OPToolboxItem;Company.MobileDSL.Dsl.dll", 
					"Company.MobileDSL.OPToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"OP", 
					"@OPToolboxBitmap;Company.MobileDSL.Dsl.dll", 
					0xff00ff,
					Index = 10)]
	[VSShell::ProvideStaticToolboxItem("Company.MobileDSL.MobileDSLToolboxTab",
					"@CToolboxItem;Company.MobileDSL.Dsl.dll", 
					"Company.MobileDSL.CToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"C", 
					"@CToolboxBitmap;Company.MobileDSL.Dsl.dll", 
					0xff00ff,
					Index = 11)]
	[VSShell::ProvideStaticToolboxItem("Company.MobileDSL.MobileDSLToolboxTab",
					"@Controller_ToolboxItem;Company.MobileDSL.Dsl.dll", 
					"Company.MobileDSL.Controller_ToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"Controller_", 
					"@Controller_ToolboxBitmap;Company.MobileDSL.Dsl.dll", 
					0xff00ff,
					Index = 12)]
	[VSShell::ProvideStaticToolboxItem("Company.MobileDSL.MobileDSLToolboxTab",
					"@State_ToolboxItem;Company.MobileDSL.Dsl.dll", 
					"Company.MobileDSL.State_ToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"State_", 
					"@State_ToolboxBitmap;Company.MobileDSL.Dsl.dll", 
					0xff00ff,
					Index = 13)]
	[VSShell::ProvideStaticToolboxGroup("@UI FormsToolboxTab;Company.MobileDSL.Dsl.dll", "Company.MobileDSL.UI FormsToolboxTab")]
	[VSShell::ProvideStaticToolboxItem("Company.MobileDSL.UI FormsToolboxTab",
					"@EventToolboxItem;Company.MobileDSL.Dsl.dll", 
					"Company.MobileDSL.EventToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"Event", 
					"@EventToolboxBitmap;Company.MobileDSL.Dsl.dll", 
					0xff00ff,
					Index = 14)]
	[VSShell::ProvideStaticToolboxItem("Company.MobileDSL.UI FormsToolboxTab",
					"@ShowFormToolboxItem;Company.MobileDSL.Dsl.dll", 
					"Company.MobileDSL.ShowFormToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"ShowForm", 
					"@ShowFormToolboxBitmap;Company.MobileDSL.Dsl.dll", 
					0xff00ff,
					Index = 15)]
	[VSShell::ProvideStaticToolboxItem("Company.MobileDSL.UI FormsToolboxTab",
					"@PrimitiveToolboxItem;Company.MobileDSL.Dsl.dll", 
					"Company.MobileDSL.PrimitiveToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"Primitive", 
					"@PrimitiveToolboxBitmap;Company.MobileDSL.Dsl.dll", 
					0xff00ff,
					Index = 16)]
	[VSShell::ProvideStaticToolboxItem("Company.MobileDSL.UI FormsToolboxTab",
					"@ButtonToolboxItem;Company.MobileDSL.Dsl.dll", 
					"Company.MobileDSL.ButtonToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"Button", 
					"@ButtonToolboxBitmap;Company.MobileDSL.Dsl.dll", 
					0xff00ff,
					Index = 17)]
	[VSShell::ProvideStaticToolboxItem("Company.MobileDSL.UI FormsToolboxTab",
					"@LabelToolboxItem;Company.MobileDSL.Dsl.dll", 
					"Company.MobileDSL.LabelToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"Label", 
					"@LabelToolboxBitmap;Company.MobileDSL.Dsl.dll", 
					0xff00ff,
					Index = 18)]
	[VSShell::ProvideStaticToolboxItem("Company.MobileDSL.UI FormsToolboxTab",
					"@DropBoxToolboxItem;Company.MobileDSL.Dsl.dll", 
					"Company.MobileDSL.DropBoxToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"DropBox", 
					"@DropBoxToolboxBitmap;Company.MobileDSL.Dsl.dll", 
					0xff00ff,
					Index = 19)]
	[VSShell::ProvideStaticToolboxItem("Company.MobileDSL.UI FormsToolboxTab",
					"@ListBoxToolboxItem;Company.MobileDSL.Dsl.dll", 
					"Company.MobileDSL.ListBoxToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"ListBox", 
					"@ListBoxToolboxBitmap;Company.MobileDSL.Dsl.dll", 
					0xff00ff,
					Index = 20)]
	[VSShell::ProvideStaticToolboxItem("Company.MobileDSL.UI FormsToolboxTab",
					"@StackPanelToolboxItem;Company.MobileDSL.Dsl.dll", 
					"Company.MobileDSL.StackPanelToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"StackPanel", 
					"@StackPanelToolboxBitmap;Company.MobileDSL.Dsl.dll", 
					0xff00ff,
					Index = 21)]
	[VSShell::ProvideStaticToolboxItem("Company.MobileDSL.UI FormsToolboxTab",
					"@InputToolboxItem;Company.MobileDSL.Dsl.dll", 
					"Company.MobileDSL.InputToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"Input", 
					"@InputToolboxBitmap;Company.MobileDSL.Dsl.dll", 
					0xff00ff,
					Index = 22)]
	[VSShell::ProvideEditorFactory(typeof(MobileDSLEditorFactory), 103, TrustLevel = VSShellInterop::__VSEDITORTRUSTLEVEL.ETL_AlwaysTrusted)]
	[VSShell::ProvideEditorExtension(typeof(MobileDSLEditorFactory), "." + Constants.DesignerFileExtension, 50)]
	[VSShell::ProvideEditorLogicalView(typeof(MobileDSLEditorFactory), "{7651A702-06E5-11D1-8EBD-00A0C90F26EA}")] // Designer logical view GUID i.e. VSConstants.LOGVIEWID_Designer
	[DslShell::ProvideRelatedFile("." + Constants.DesignerFileExtension, Constants.DefaultDiagramExtension,
		ProjectSystem = DslShell::ProvideRelatedFileAttribute.CSharpProjectGuid,
		FileOptions = DslShell::RelatedFileType.FileName)]
	[DslShell::ProvideRelatedFile("." + Constants.DesignerFileExtension, Constants.DefaultDiagramExtension,
		ProjectSystem = DslShell::ProvideRelatedFileAttribute.VisualBasicProjectGuid,
		FileOptions = DslShell::RelatedFileType.FileName)]
	[DslShell::RegisterAsDslToolsEditor]
	[global::System.Runtime.InteropServices.ComVisible(true)]
	[DslShell::ProvideBindingPath]
	[DslShell::ProvideXmlEditorChooserBlockSxSWithXmlEditor(@"MobileDSL", typeof(MobileDSLEditorFactory))]

	internal abstract partial class MobileDSLPackageBase : DslShell::ModelingPackage
	{
		protected global::Company.MobileDSL.MobileDSLToolboxHelper toolboxHelper;	
		
		/// <summary>
		/// Initialization method called by the package base class when this package is loaded.
		/// </summary>
		protected override void Initialize()
		{
			base.Initialize();

			// Register the editor factory used to create the DSL editor.
			this.RegisterEditorFactory(new MobileDSLEditorFactory(this));
			
			// Initialize the toolbox helper
			toolboxHelper = new global::Company.MobileDSL.MobileDSLToolboxHelper(this);

			// Create the command set that handles menu commands provided by this package.
			MobileDSLCommandSet commandSet = new MobileDSLCommandSet(this);
			commandSet.Initialize();
			
			// Create the command set that handles cut/copy/paste commands provided by this package.
			MobileDSLClipboardCommandSet clipboardCommandSet = new MobileDSLClipboardCommandSet(this);
			clipboardCommandSet.Initialize();
			
			// Register the model explorer tool window for this DSL.
			this.AddToolWindow(typeof(MobileDSLExplorerToolWindow));

			// Initialize Extension Registars
			// this is a partial method call
			this.InitializeExtensions();

			// Add dynamic toolbox items
			this.SetupDynamicToolbox();
		}

		/// <summary>
		/// Partial method to initialize ExtensionRegistrars (if any) in the DslPackage
		/// </summary>
		partial void InitializeExtensions();
		
		/// <summary>
		/// Returns any dynamic tool items for the designer
		/// </summary>
		/// <remarks>The default implementation is to return the list of items from the generated toolbox helper.</remarks>
		protected override global::System.Collections.Generic.IList<DslDesign::ModelingToolboxItem> CreateToolboxItems()
		{
			try
			{
				Debug.Assert(toolboxHelper != null, "Toolbox helper is not initialized");
				return toolboxHelper.CreateToolboxItems();
			}
			catch(global::System.Exception e)
			{
				global::System.Diagnostics.Debug.Fail("Exception thrown during toolbox item creation.  This may result in Package Load Failure:\r\n\r\n" + e);
				throw;
			}
		}
		
		
		/// <summary>
		/// Given a toolbox item "unique ID" and a data format identifier, returns the content of
		/// the data format. 
		/// </summary>
		/// <param name="itemId">The unique ToolboxItem to retrieve data for</param>
		/// <param name="format">The desired format of the resulting data</param>
		protected override object GetToolboxItemData(string itemId, DataFormats.Format format)
		{
			Debug.Assert(toolboxHelper != null, "Toolbox helper is not initialized");
		
			// Retrieve the specified ToolboxItem from the DSL
			return toolboxHelper.GetToolboxItemData(itemId, format);
		}
	}

}

//
// Package attributes which may need to change are placed on the partial class below, rather than in the main include file.
//
namespace Company.MobileDSL
{
	/// <summary>
	/// Double-derived class to allow easier code customization.
	/// </summary>
	[VSShell::ProvideMenuResource("1000.ctmenu", 1)]
	[VSShell::ProvideToolboxItems(1)]
	[global::Microsoft.VisualStudio.TextTemplating.VSHost.ProvideDirectiveProcessor(typeof(global::Company.MobileDSL.MobileDSLDirectiveProcessor), global::Company.MobileDSL.MobileDSLDirectiveProcessor.MobileDSLDirectiveProcessorName, "A directive processor that provides access to MobileDSL files")]
	[global::System.Runtime.InteropServices.Guid(Constants.MobileDSLPackageId)]
	internal sealed partial class MobileDSLPackage : MobileDSLPackageBase
	{
	}
}